apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-authserver" (include "azerothcore.fullname" .) }}
  labels:
    {{- include "azerothcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: authserver
  {{- with .Values.authserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.authserver.service.type }}
  ports:
    - name: auth
      port: {{ .Values.authserver.service.port }}
      targetPort: auth
      {{- if and (ne .Values.authserver.service.type "ClusterIP") .Values.authserver.service.nodePort }}
      nodePort: {{ .Values.authserver.service.nodePort }}
      {{- end }}
  selector:
    {{- include "azerothcore.selectorLabels" (dict "ctx" . "component" "authserver") | nindent 4 }}
