{{- if and .Values.mysql.enabled (not .Values.mysql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azerothcore.db.secretName" . }}
  labels:
    {{- include "azerothcore.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mysql.existingSecretPasswordKey }}: {{ .Values.mysql.rootPassword | quote }}
{{- end }}
