apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-worldserver" (include "azerothcore.fullname" .) }}
  labels:
    {{- include "azerothcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: worldserver
  {{- with .Values.worldserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.worldserver.service.type }}
  ports:
    - name: world
      port: {{ .Values.worldserver.service.port }}
      targetPort: world
      {{- if and (ne .Values.worldserver.service.type "ClusterIP") .Values.worldserver.service.nodePort }}
      nodePort: {{ .Values.worldserver.service.nodePort }}
      {{- end }}
  selector:
    {{- include "azerothcore.selectorLabels" (dict "ctx" . "component" "worldserver") | nindent 4 }}
---
{{- if .Values.worldserver.soap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-worldserver-soap" (include "azerothcore.fullname" .) }}
  labels:
    {{- include "azerothcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: worldserver
spec:
  type: ClusterIP
  ports:
    - name: soap
      port: 7878
      targetPort: soap
  selector:
    {{- include "azerothcore.selectorLabels" (dict "ctx" . "component" "worldserver") | nindent 4 }}
{{- end }}
